addons:
 apt:
  packages:
  - valgrind
before_install:
  - pip install --user cpp-coveralls
language: c
script:
- make memtest && make clean && make -B EXTRA_CFLAGS="-pg -fprofile-arcs -ftest-coverage" test
after_success:
- coveralls --gcov-options '-o ./ src/*.c'
